// prerender.js - Static Site Generation (SSG) configuration
import { getPageMeta } from './src/lib/pageMeta';

export async function render(url) {
  try {
    const meta = getPageMeta(url);
    return {
      html: '', // Actual HTML will be generated by entry-server.tsx
      meta,
      status: 200
    };
  } catch (error) {
    return {
      html: '',
      meta: { title: 'Error', description: '' },
      status: 500
    };
  }
}

export function getTitle(url) {
  return getPageMeta(url).title || 'London Glazing Specialists';
}

export function getDescription(url) {
  return getPageMeta(url).description || 'Professional secondary glazing solutions';
}

// Export all routes that should be prerendered
export default {
  routes: [
    '/',
    '/about',
    '/contact',
    '/specialized-services',
    '/commercial/office-buildings',
    '/secondary-glazing-noise-reduction',
    '/specialized/acoustic-glazing',
    '/specialized/uv-protection',
    '/residential/sash-windows',
    // Add all other routes that need prerendering
  ],
  render,
  getTitle,
  getDescription,
  // Add caching headers for better performance
  cacheControl: {
    maxAge: 86400, // 1 day
    staleWhileRevalidate: 604800 // 1 week
  }
};